### ISSUE TITLE
what are the dependencies for it to work?

### ISSUE THREAD

**Issue by nuliknol** [fzipp/pythia#24]
What packages have to be installed?

I am getting this error:

/usr/local/go/src/crypto/tls/cipher_suites.go:18:2: could not import golang_org/x/crypto/chacha20poly1305 (cannot find package "golang_org/x/crypto/chacha20poly1305" in any of:
	/usr/local/go/src/golang_org/x/crypto/chacha20poly1305 (from $GOROOT)
	/home/niko/go/src/golang_org/x/crypto/chacha20poly1305 (from $GOPATH))
/usr/local/go/src/crypto/tls/key_agreement.go:20:2: could not import golang_org/x/crypto/curve25519 (cannot find package "golang_org/x/crypto/curve25519" in any of:

**Comment by nuliknol** [comment]
you renamed "golang.org" into "golang_org" and because of this your package is broken now, you can't install it. Hopefully I did "cp -a golang.org golang_org"  in my $GOPATH/src and it works now.

**Comment by Thunder-X** [comment]
It seems that this package doesn't honor "vendor" import path, which is the reason for failure. Anyone figured out how to fix it?

**Comment by Thunder-X** [comment]
I made a pull request that should fixes this.

**Comment by fzipp** [comment]
Sorry for the inconveniences. I haven't updated Pythia for a while. Pythia uses vgo now, based on your work for dep.
